### 3-1 네이버 책 검색 API 호출하기

In [36]:
import requests
import pprint
import os
from dotenv import load_dotenv

# .env 파일에서 환경 변수 로드
load_dotenv()

# 환경 변수에서 값 읽기
client_id = os.getenv("NAVER_CLIENT_ID")  # .env 파일의 NAVER_CLIENT_ID
client_secret = os.getenv("NAVER_CLIENT_SECRET")  # .env 파일의 NAVER_CLIENT_SECRET

headers = {
    'X-Naver-Client-Id': client_id,
    'X-Naver-Client-Secret': client_secret,
}

def search_books(query):  
 # query string 문자열을 dict 선언
 payload = {
    'query': query,#'파이썬',
    'display': 50,
    'sort': 'sim'
    }

 url = 'https://openapi.naver.com/v1/search/book.json' #?query=파이썬&display=100&sort=sim

 # requests get(url, params, headers) 요청 
 res = requests.get(url, params=payload, headers=headers)
# json() 함수로 응답 결과 가져오기
 return res.json()

response = search_books("파이썬")

### 1. 검색어로  찾은  책 목록을 json 파일로 저장하기

In [37]:
import os
import json

if not os.path.isdir("data"):
    os.mkdir('data')

with open("data/books.json", "w", encoding="utf-8") as f:
    json.dump(response, f, ensure_ascii=False, indent=5)

#### 2. books.json 파일을 Pandas DataFrame으로 저장하기

In [38]:
import pandas as pd

with open("data/books.json", "r", encoding="utf-8") as f:
    data = json.load(f)

book_df = pd.DataFrame(items)  # items 키 안에 책 목록

### 3. 검색어로 찾은 책 목록 출력하기

In [47]:
import json
import pandas as pd
from IPython.display import display

# 저장된 JSON 파일 열기
with open("data/books.json", "r", encoding="utf-8") as f:
    data = json.load(f)


if isinstance(data, list):
    book_df = pd.DataFrame(data)

# 책 목록 전체 출력 (or 일부)
pd.set_option('display.max_colwidth', None)  # 줄바꿈 없이 제목 다 보기
display(book_df[['title', 'author', 'publisher']].head(5))  # 상위 10개만 보기!

,title,author,publisher
0,"혼자 만들면서 공부하는 파이썬 (37개 라이브러리와 API로 보고서, 차트, 게임, 맵, AI 챗봇 만들기|저자 직강 유튜브 강의, 오픈 채팅 제공)",문현일,한빛미디어
1,혼자 공부하는 파이썬 (1:1 과외하듯 배우는 프로그래밍 자습서),윤인성,한빛미디어
2,Do it! 점프 투 파이썬 (중학생도 첫날부터 실습하는 초고속 입문서),박응용,이지스퍼블리싱
3,밑바닥부터 시작하는 딥러닝 1(리마스터판) (파이썬으로 익히는 딥러닝 이론과 구현),사이토 고키,한빛미디어
4,파이썬,홍의경,생능출판

In [48]:
import pandas as pd
import json
from IPython.display import display

# 저장된 JSON 파일 읽기
with open("data/books.json", "r", encoding="utf-8") as f:
    data = json.load(f)

# 데이터프레임 생성
book_df = pd.DataFrame(items)

# discount 컬럼을 숫자로 변환 (문자열로 저장된 경우 있음)
book_df['discount'] = pd.to_numeric(book_df['discount'], errors='coerce')

# 2만원 이상 필터링
filtered_df = book_df[book_df['discount'] >= 20000]

# 필요한 컬럼만 선택
selected_columns = ['title', 'author', 'discount', 'publisher', 'pubdate']
filtered_df = filtered_df[selected_columns]

# 할인 가격 내림차순 정렬 + 인덱스 초기화
filtered_df = filtered_df.sort_values(by='discount', ascending=False).reset_index(drop=True)

# 결과 출력
display(filtered_df)

,title,author,discount,publisher,pubdate
0,으뜸 파이썬 (프로그래밍을 사랑하는 두 교수가 작정하고 쓴),박동규^강영민,31680,생능출판,20200217
1,파이썬,Y. Daniel Liang,31500,에피스테메,20180302
2,으뜸 파이썬 (개정판),박동규^강영민,31280,생능출판,20240614
3,파이썬 마스터 (실생활 융합 예제로 배우는),김종훈^김동건,31040,한빛아카데미,20250117
4,파이썬 머신러닝 완벽 가이드 (다양한 캐글 예제와 함께 기초 알고리즘부터 최신 기법까지 배우는),권철민,29800,위키북스,20220421
5,파이썬,홍의경,29440,생능출판,20220309
6,독학 파이썬,야마다 요시히로,28800,정보문화사,20241220
7,새내기 파이썬,천인국,27600,생능출판,20220630
8,파이썬의 정석,조용주^임좌상,26820,길벗캠퍼스,20230110
9,디딤돌 파이썬 (구조적 프로그래밍으로 설명한 파이썬 기초),이찬수,26100,인피니티북스,20220823
10,파이썬 + AI (코드조각과 실행화면으로 배우는 코딩),안용제^김남규,25200,디지털북스,20240715
11,파이썬의 신 (프로그래밍 언어를 배운다는 것),김주현,24300,로드북,20161223
12,내공의 파이썬 (한 권으로 끝내는 초보자용 코딩 입문서),한선관,24300,자유아카데미,20250315
13,파이썬 플러스,최희식,23750,인피니티북스,20240731
14,파이썬,김영천,23750,기한재,20200225
15,밑바닥부터 시작하는 딥러닝 1(리마스터판) (파이썬으로 익히는 딥러닝 이론과 구현),사이토 고키,23400,한빛미디어,20250124
16,파이썬 연습 (개정판),김기용,23400,그린,20220225
17,"혼자 만들면서 공부하는 파이썬 (37개 라이브러리와 API로 보고서, 차트, 게임, 맵, AI 챗봇 만들기|저자 직강 유튜브 강의, 오픈 채팅 제공)",문현일,23400,한빛미디어,20250214
18,파이썬 프로그래밍 (기초부터 딥러닝까지),허준,22500,성안당,20250312
19,엑셀X파이썬 (엑셀이 파이썬을 품었다),정성일,22500,길벗,20240730
20,파이썬 입문 (3step으로 확실하게 배우는),야마다 요시히로^야마다 나미,22500,시그마프레스,20210105
21,파이썬 (다양한 예제로 알로리즘 쉽게 분석하기),김유진,22500,다본,20190410
22,코딩 자율학습 나도코딩의 파이썬 입문 (초보자 눈높이에 맞춘 친절한 프로그래밍 자습서),나도코딩,21600,길벗,20230220
23,파이썬을 이용한 통계수학,권세혁,21560,자유아카데미,20250315
24,파이썬 올인원 (기초부터 데이터분석까지),이지민^임희경,20700,연두에디션,20230904

#### 4. 검색어로  찾은  책 목록 중에서 출판사가 인피니티북스인 책만 출력하기

In [49]:
from IPython.display import display


# "인피니티북스"인 책만 필터링
infinity_df = book_df[book_df['publisher'] == '인피니티북스']

# 이미지와 설명 컬럼 제거
infinity_df = infinity_df.drop(columns=['image', 'description'], errors='ignore')

# 인덱스 초기화
infinity_df.reset_index(drop=True, inplace=True)

# 출력
infinity_df

display(infinity_df)

,title,link,author,discount,publisher,pubdate,isbn
0,파이썬,https://search.shopping.naver.com/book/catalog/32489150082,천인국,12000,인피니티북스,20170830,9791185578330
1,파이썬 플러스,https://search.shopping.naver.com/book/catalog/49800327644,최희식,23750,인피니티북스,20240731,9791192373362
2,디딤돌 파이썬 (구조적 프로그래밍으로 설명한 파이썬 기초),https://search.shopping.naver.com/book/catalog/34233217628,이찬수,26100,인피니티북스,20220823,9791192373058

### 3-2. 네이버 쇼핑 검색 API 호출하기

##### 1. 검색어로  찾은  책 목록을 json 파일로 저장하기
##### 2. shops.json 파일을 Pandas DataFrame로 저장하기

In [72]:
import requests
import os
import json
import pandas as pd
from dotenv import load_dotenv

# .env 파일에서 환경 변수 로드
load_dotenv()

# 환경 변수에서 값 읽기
client_id = os.getenv("NAVER_CLIENT_ID")  # .env 파일의 NAVER_CLIENT_ID
client_secret = os.getenv("NAVER_CLIENT_SECRET")  # .env 파일의 NAVER_CLIENT_SECRET

headers = {
    'X-Naver-Client-Id': client_id,
    'X-Naver-Client-Secret': client_secret,
}

def search_shops(query):  
 # query string 문자열을 dict 선언
 payload = {
    'query': query,#'가디건',
    'display': 50,
    'sort': 'sim'
    }

 url = 'https://openapi.naver.com/v1/search/shop.json' #?query=파이썬&display=100&sort=sim

 # requests get(url, params, headers) 요청 
 res = requests.get(url, params=payload, headers=headers)
 # json() 함수로 응답 결과 가져오기
 items_data = res.json().get('items', [])
 
 
 # 저장 경로 없으면 생성
 if not os.path.isdir("data"):
     os.mkdir("data")

 # JSON 저장
 with open("data/shops.json", "w", encoding="utf-8") as f:
     json.dump(items_data, f, ensure_ascii=False, indent=4)

 print(f"검색 결과가 'data/shops.json'에 저장되었습니다. (검색어: {query})")
 return items_data


items = search_shops("가디건")
print(f"총 {len(items)}개 상품을 불러왔습니다.")

검색 결과가 'data/shops.json'에 저장되었습니다. (검색어: 가디건)
총 50개 상품을 불러왔습니다.

##### 3. 검색어로  찾은  Shop의 상품  목록 출력하기

In [ ]:
import pandas as pd
import json

# JSON 파일 읽어서 DataFrame으로 변환
def load_shops_to_df():
    with open("data/shops.json", "r", encoding="utf-8") as f:
        items = json.load(f)
    
    df = pd.DataFrame(items)
    return df

df = load_shops_to_df()

# 데이터프레임 확인
print(f"불러온 상품 수: {len(df)}개")
display(df.head())

✅ 불러온 상품 수: 50개

,title,link,image,lprice,hprice,mallName,productId,productType,brand,maker,category1,category2,category3,category4
0,백화점3-5일배송 폴로 <b>가디건</b> 걸즈 걸스 랄프로렌 꽈배기 블랙 화이트 핑크 헌터네이비XL,https://smartstore.naver.com/main/products/6672150068,https://shopping-phinf.pstatic.net/main_8421665/84216650390.13.jpg,64900,,나우인뉴욕,84216650390,2,폴로랄프로렌,폴로랄프로렌,패션의류,여성의류,카디건,
1,봄 가을 간절기 라운드 루즈핏 크롭 <b>가디건</b> 레드 그린 핑크 화이트 블랙 옐로우,https://smartstore.naver.com/main/products/5466947569,https://shopping-phinf.pstatic.net/main_8301144/83011442056.2.jpg,19900,,ARUMY,83011442056,2,,,패션의류,여성의류,카디건,
2,부드러운 캐시미어 크롭 <b>가디건</b> 숏 라운드 니트<b>가디건</b> 여성 <b>가디건</b> 봄 간절기 레드 핑크,https://smartstore.naver.com/main/products/4828155463,https://shopping-phinf.pstatic.net/main_8237267/82372678315.3.jpg,18900,,코이블리,82372678315,2,,,패션의류,여성의류,카디건,
3,[백화점3-5일배송] 폴로 <b>가디건</b> 니트 걸즈 랄프로렌 블랙 화이트 핑크 헌터네이비XL L,https://smartstore.naver.com/main/products/8450462001,https://shopping-phinf.pstatic.net/main_8599496/85994962324.3.jpg,63900,,트위티 155,85994962324,2,폴로랄프로렌,폴로랄프로렌,패션의류,여성의류,카디건,
4,[국내발송 + 선물포장] 폴로 랄프로렌 여아 아기 코튼 베이비 <b>가디건</b> 핑크 옐로우 화이트,https://smartstore.naver.com/main/products/9459545518,https://shopping-phinf.pstatic.net/main_8700404/87004045841.1.jpg,69000,,리틀데이즈,87004045841,2,폴로랄프로렌,폴로랄프로렌,출산/육아,유아동의류,카디건,

##### 4. 검색어로  찾은  Shop의 상품  목록 중에서 가격이 50,000원 이하인 상품만 출력하기

In [76]:
def filter_by_price(df, max_price=50000):
    # 'lprice'는 문자열이라 정수로 변환 필요!
    df['lprice'] = df['lprice'].astype(int)
    
    # 조건에 맞는 상품 필터링
    filtered_df = df[df['lprice'] <= max_price]
    
    # 필요한 컬럼만 선택
    result_df = filtered_df[['brand', 'lprice', 'mallName', 'link']]
    
    # 가격 기준 오름차순 정렬 + 인덱스 초기화
    result_df = result_df.sort_values(by='lprice').reset_index(drop=True)
    
    return result_df
df = load_shops_to_df()  # 이전 단계에서 만든 DataFrame 불러오기
cheap_items = filter_by_price(df)

# 결과 확인
print(f"50,000원 이하 상품 개수: {len(cheap_items)}개")
display(cheap_items.head())

50,000원 이하 상품 개수: 25개

,brand,lprice,mallName,link
0,H&M,17512,네이버,https://search.shopping.naver.com/catalog/51781610172
1,,18900,코이블리,https://smartstore.naver.com/main/products/4828155463
2,,18900,코이블리,https://smartstore.naver.com/main/products/4382440024
3,,19800,로이앤한나,https://smartstore.naver.com/main/products/4901850589
4,,19900,ARUMY,https://smartstore.naver.com/main/products/5466947569

##### 4. 검색어로  찾은  Shop의 상품  목록 중에서 특정 쇼핑몰 상품만 출력하기

In [78]:
def filter_by_mall(df, mall_name):
    # 가격 컬럼 숫자로 변환
    df['lprice'] = df['lprice'].astype(int)
    
    # mallName이 일치하는 상품만 선택
    mall_df = df[df['mallName'] == mall_name]
    
    # lprice ~ brand까지 슬라이싱 (열 순서 보장됨)
    cols = df.columns.tolist()
    start_idx = cols.index('lprice')
    end_idx = cols.index('brand') + 1
    selected_cols = cols[start_idx:end_idx]
    
    # 필요한 열만 선택, 가격 오름차순 정렬, 인덱스 초기화
    result_df = mall_df[selected_cols].sort_values(by='lprice').reset_index(drop=True)
    
    return result_df

df = load_shops_to_df()

# 예: '11번가' 상품만 보기
mall_items = filter_by_mall(df, "네이버")

print(f"'네이버' 상품 수: {len(mall_items)}개")
display(mall_items.head())

'네이버' 상품 수: 12개

   lprice hprice mallName    productId productType     brand
0   17512             네이버  51781610172           1       H&M
1   23000             네이버  51143733510           1       리스트
2   28070             네이버  43475137325           1  비비안웨스트우드
3   31416             네이버  49541497760           1   제너럴아이디어
4   32400             네이버  53287208769           1   제너럴아이디어